### ISSUE TITLE
Setting server IP/Name

### ISSUE THREAD

**Issue by crhatfield** [ravetroll/BedrockService#11]
for some odd reason, my 10g fiber network card wont allow me to loop-back with "localhost", would be nice to be able to set that to specifically 127.0.0.1 or my LAN IP to be able to try a few other work arounds. Currently I can't even use the "client" :/

**Comment by miweber67** [comment]
> 
> 
> for some odd reason, my 10g fiber network card wont allow me to loop-back with "localhost", would be nice to be able to set that to specifically 127.0.0.1 or my LAN IP to be able to try a few other work arounds. Currently I can't even use the "client" :/

Just curious if this bit from the current docs helps in your case?

On some systems, when you wish to connect to the server using a client running on the same machine as the server is running on, you will need to exempt the Minecraft client from UWP loopback restrictions:

    CheckNetIsolation.exe LoopbackExempt –a –p=S-1-15-2-1958404141-86561845-1752920682-3514627264-368642714-62675701-733520436

**Comment by benskev** [comment]
did this work? I'm having a similar issue

**Comment by hubaksis** [comment]
Worked for me.
This is actually written in the official "bedrock_server_how_to.html" file
![image](https://user-images.githubusercontent.com/13341477/170582394-9ae485e2-ed19-4a48-bbdb-f85a3247710a.png)
