### ISSUE TITLE
Getting error when starting the service

### ISSUE THREAD

**Issue by ruanhoo** [ravetroll/BedrockService#14]
I'm getting below error when starting the service. Running on Windows 11, the bedrock server itself could be started normally without using bedrockservice. Wondering what could be the reason?

E:\MCServer\bedrockservice start
ERROR [1] (:0) - The service failed to start.
System.ServiceProcess.TimeoutException: Time out has expired and the operation has not been completed.
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   at Topshelf.Runtime.Windows.WindowsHostEnvironment.StartService(String serviceName, TimeSpan startTimeOut)
   at Topshelf.Hosts.StartHost.Run()

**Comment by ravetroll** [comment]
Have you tried running E:\MCServer\bedrockservice from the command prompt (so run without the start command).  This would show you the console and you should see the bedrock server startup procedures

**Comment by ruanhoo** [comment]
> Have you tried running E:\MCServer\bedrockservice from the command prompt (so run without the start command). This would show you the console and you should see the bedrock server startup procedures

Hi, @ravetroll  Thanks for your reply. By running bedrockservice directly, I was able to see the actual error, which is due to I put WCFPortNumber with a same port as MCserver's port. This is resolved by changing it to another port. It works great. Thanks!
