### ISSUE TITLE
Service unable to start with two bedrock instances.

### ISSUE THREAD

**Issue by matt1235r** [ravetroll/BedrockService#4]
Hello there, thanks for creating this!

I am unable to get the service to start with two instances of bedrock server. The service starts fine with either server instance on their own. 

The error I receive when trying to start the service manually is:

`C:\Bedrock Server Creative\Windows Service>bedrockservice start
ERROR [1] (:0) - The service failed to start.
System.ServiceProcess.TimeoutException: Time out has expired and the operation has not been completed.
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   at Topshelf.Runtime.Windows.WindowsHostEnvironment.StartService(String serviceName, TimeSpan startTimeOut)
   at Topshelf.Hosts.StartHost.Run()`

I have attached my config file to the issue.

Thanks again! 

[Config File.txt](https://github.com/ravetroll/BedrockService/files/4357033/Config.File.txt)

**Comment by ravetroll** [comment]
Your config file looks fine. If you run the two instances manually do they run correctly?  On my test machine I have SSD's and small worlds so it starts pretty quickly.  That said, I have done a test starting up 5 worlds and it managed that so 2 should be possible.  How long does it take for your system to start a world?  The timeout suggests that it is not able to get started in the timeframe allocated to starting a service.

**Comment by matt1235r** [comment]
The two instances start fine manually. They both have fairly large worlds, taking about 15 seconds to start up each.

Is there any way to adjust the timeout or is it hard coded?

Thanks again.

**Comment by ravetroll** [comment]
I think it might be possible to extend the timeout.  I will have a look into it and get back to you.

**Comment by ravetroll** [comment]
I have added a request to allow more startup time to the service.  Download a new copy and let me know if that fixes it.

**Comment by ravetroll** [comment]
I haven't heard back from OP if this resolved the issue, so I am going to mark this as closed.

**Comment by matt1235r** [comment]
Sorry for not responding sooner! I can confirm the issue is now fixed following your update.

Thanks!
