### ISSUE TITLE
Issue commands to server

### ISSUE THREAD

**Issue by eduo** [ravetroll/BedrockService#5]
Hello

Currently there's a bug in bedrock server that doesn't allow settings issued from the client. 

Would it be possible to set default comments to execute at startup, in the same way they would normally be available in the console?

**Comment by ravetroll** [comment]
Once the server starts, you want to enter a series of standard commands that would normally be issued from the console.  It should be possible for me to add it and include them in an array in the config file.

**Comment by ravetroll** [comment]
I have added the ability to send startup commands

**Comment by brunofvalli** [comment]
I assume there is no way to see the console or issue commands to it, right?
If that is true are you open to pull requests?

**Comment by brunofvalli** [comment]
What I mean is issue commands at anytime. While the service is running.

**Comment by brunofvalli** [comment]
@ravetroll 
I have created the pull request for the Client console code. Let me know what you think.
