### ISSUE TITLE
Fixed time backup schedule

### ISSUE THREAD

**Issue by Thelmos** [ravetroll/BedrockService#6]
I'm using a one day interval for backups. It works fine while server its up forever, but when you restart it frecuently (new versions, windows updates, power failure, etc...) you get no backup for 2 or 3 days, every time I have to restart my server, backup is delayed for another 24 hours. Also, with this method, it's hard to match backups at off-peak hours.

It would be nice to just be able to set the time of day we want the backup to take place.

A more professional approach could be to use a cron style pattern to schedule backups, but I don't know if this complexity is worth it.

**Comment by ravetroll** [comment]
I have added a cron based backup scheduling that should achieve your objectives
