### ISSUE TITLE
Enable Updates as well as control over backups

### ISSUE THREAD

**Issue by eduo** [ravetroll/BedrockService#7]
Currently upgrading is a bit of a PITA.

Please implement upgrading by restarting the service, so when it's restarted it checks for a newer version and if existing, applies it (not replacing the server.properties, permissions and whitelist files, as well as added folders in behaviour packs and resource packs.

Also, start of the service could scan both behaviour and resource packs and add the necessary entries to enable them to valid known packs json.

Lastly: Restart should prompt a backup if more than a day has passed since the last one, but other backups should be configurable on a specific hour and frequency.

**Comment by ravetroll** [comment]
I can't see upgrading the Minecraft bedrock service being in the scope of this project.

I have added an improved cron based backup scheduling
